services:
  - type: web
    name: ecomad-backend
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8080
      - key: CORS_ORIGIN
        value: "*"
      - key: COMMON_RATE_LIMIT_MAX_REQUESTS
        value: 1000
      - key: COMMON_RATE_LIMIT_WINDOW_MS
        value: 1000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
